import { ArchiveIcon, FileTextIcon } from "@radix-ui/react-icons";
import { SlidersHorizontalIcon, SparklesIcon, ActivityIcon } from "lucide-react";
import { Particles } from "@/components/magicui/particles";
import { cn } from "@/lib/utils";
import {AnimatedBeamMultipleOutputDemo} from "@/components/example/animated-beam-multiple-outputs";
import {AnimatedListDemo} from "@/components/example/animated-list-demo";
import { BentoCard, BentoGrid } from "@/components/magicui/bento-grid";
import { Marquee } from "@/components/magicui/marquee";

const files = [
    {
        name: "experiment.json",
        body: "Summary of the gene expression experiment, including number of samples, features, and metadata related to biological conditions under study.",
    },
    {
        name: "clusters.json",
        body: "Clustering output from KMeans, DBSCAN, or Agglomerative algorithms — each data point is assigned to a cluster based on similarity in expression profiles.",
    },
    {
        name: "xai_report.json",
        body: "Explainable AI insights generated by MedAI, interpreting cluster structures, highlighting anomalies, and suggesting biological implications.",
    },
    {
        name: "gene_expression_matrix.csv",
        body: "Normalized gene expression matrix with rows as genes and columns as samples, used as input for clustering and downstream analysis.",
    },
    {
        name: "medai_summary.txt",
        body: "Natural language summary generated by the MedAI model, offering a comprehensive interpretation of the dataset, clusters, and biological context.",
    },
];


const features = [
    {
        Icon: ActivityIcon,
        name: "Discover MedJourney",
        description: "Explore how MedJourney empowers clinicians with AI-driven clustering and visualization tools.",
        href: "https://medjourney-ai.hashnode.space/",
        cta: "Get Started",
        className: "w-full h-auto items-center justify-between shadow-md bg-zinc-50 rounded-xl",
        background: (
            <Particles
                className="absolute inset-0 z-0"
                quantity={300}
                ease={100}
                color="#193cb8"
                refresh
            />
        ),
    },
    {
        Icon: ArchiveIcon,
        name: "Create New Projects",
        description: "keep all your work organized in a single place",
        href: "#",
        view: "projects",
        cta: "Create a new project",
        className: "col-span-3 lg:col-span-1",
        background: (
            <Marquee
                pauseOnHover
                className="absolute top-10 [--duration:20s] [mask-image:linear-gradient(to_top,transparent_40%,#000_100%)] "
            >
                {files.map((f, idx) => (
                    <figure
                        key={idx}
                        className={cn(
                            "relative w-32 cursor-pointer overflow-hidden rounded-xl border p-4",
                            "border-gray-950/[.1] bg-gray-950/[.01] hover:bg-gray-950/[.05]",
                            "dark:border-gray-50/[.1] dark:bg-gray-50/[.10] dark:hover:bg-gray-50/[.15]",
                            "transform-gpu blur-[1px] transition-all duration-300 ease-out hover:blur-none",
                        )}
                    >
                        <div className="flex flex-row items-center gap-2">
                            <div className="flex flex-col">
                                <figcaption className="text-sm font-medium dark:text-white ">
                                    {f.name}
                                </figcaption>
                            </div>
                        </div>
                        <blockquote className="mt-2 text-xs">{f.body}</blockquote>
                    </figure>
                ))}
            </Marquee>
        ),
    },
    {
        Icon: SlidersHorizontalIcon,
        name: "Various Clustering Algorithms",
        description: "Choose the Algorithm that suits your needs best",
        href: "#",
        view: "dashboard",
        cta: "Start Analyzing",
        className: "col-span-3 lg:col-span-2",
        background: (
            <AnimatedListDemo className="absolute right-2 top-4 h-[300px] w-full scale-75 border-none transition-all duration-300 ease-out [mask-image:linear-gradient(to_top,transparent_10%,#000_100%)] group-hover:scale-90" />
        ),
    },
    {
        Icon: SparklesIcon,
        name: "MedAI, your Data Science assistant",
        description: "Unveil new insights on your data with the help of MedAI",
        view: "dashboard",
        className: "col-span-3 lg:col-span-2",
        background: (
            <AnimatedBeamMultipleOutputDemo className="absolute right-2 top-4 h-[300px] border-none transition-all duration-300 ease-out [mask-image:linear-gradient(to_top,transparent_10%,#000_100%)] group-hover:scale-105" />
        ),
    },
    {
        Icon: FileTextIcon,
        name: "File Preprocessing",
        description: "Each analysis start from a serial matrix file to get the best result possible",
        className: "col-span-3 lg:col-span-1",
        background: ( <Particles
            className="absolute inset-0 z-0"
            quantity={300}
            ease={100}
            color="#193cb8"
            refresh
        />),
    },
];

type TakeATourViewProps = {
    setActiveView: (view: "dashboard" | "projects" | "askMedAI") => void;
};


export function TakeATourView({ setActiveView }: TakeATourViewProps) {

    return (
        <BentoGrid>
            {features.map((feature, idx) => (
                <BentoCard key={idx} {...feature}  onClick={() => setActiveView(feature.view as "dashboard" | "projects" | "askMedAI")}/>
            ))}
        </BentoGrid>   );
}
